name: Pre-Build Components ECR

on:
  push:

env:
  REGISTRY: public.ecr.aws
  PROJECT: p8t2q7f4/${{ github.repository }}

permissions:
      id-token: write 
      contents: read

jobs:
  production:
    name: 'Production'
    runs-on: ubuntu-24.04-arm
    
    steps:


      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::300197899440:role/ECRPrebuildPushRightsForGithubActionsRole
          aws-region: us-east-1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.PROJECT }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            # Set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.login-ecr-public.outputs.registry }}
          username: ${{ steps.login-ecr-public.outputs.docker_username }}
          password: ${{ steps.login-ecr-public.outputs.docker_password }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  development:
    name: 'Development'
    runs-on: ubuntu-24.04-arm
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::300197899440:role/ECRPrebuildPushRightsForGithubActionsRole
          aws-region: us-east-1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.PROJECT }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            # Set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
          flavor: |
            suffix=-dev.,onlatest=true

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.login-ecr-public.outputs.registry }}
          username: ${{ steps.login-ecr-public.outputs.docker_username }}
          password: ${{ steps.login-ecr-public.outputs.docker_password }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.dev
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}